// Inline style objects for the pdf_signer app (split out of Signer.tsx
// to keep components under the repo's 500-line file cap).
import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    fontFamily: "system-ui, -apple-system, sans-serif",
    background: "#f5f5f5",
    color: "#1f1f1f",
  },
  centered: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    color: "#5f6368",
    fontFamily: "system-ui, sans-serif",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "10px 16px",
    background: "#fff",
    borderBottom: "1px solid #e0e0e0",
    flexShrink: 0,
  },
  filename: { fontWeight: 600, fontSize: 14 },
  pendingBadge: {
    fontSize: 12,
    color: "#8a5a00",
    background: "#fff3d6",
    border: "1px solid #f0d48a",
    borderRadius: 999,
    padding: "3px 10px",
  },
  signedBadge: {
    fontSize: 12,
    color: "#0d652d",
    background: "#e6f4ea",
    border: "1px solid #b7dfc0",
    borderRadius: 999,
    padding: "3px 10px",
  },
  cancelledBadge: {
    fontSize: 12,
    color: "#5f6368",
    background: "#eee",
    borderRadius: 999,
    padding: "3px 10px",
  },
  pagesScroller: {
    flex: 1,
    overflow: "auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    padding: 16,
  },
  pageWrap: {
    position: "relative",
    background: "#fff",
    boxShadow: "0 1px 4px rgba(0,0,0,0.2)",
    flexShrink: 0,
  },
  highlight: {
    position: "absolute",
    border: "2px dashed #d97706",
    background: "rgba(251, 191, 36, 0.15)",
    borderRadius: 4,
    pointerEvents: "none",
  },
  highlightLabel: {
    position: "absolute",
    top: -20,
    left: 0,
    fontSize: 11,
    fontWeight: 600,
    color: "#92400e",
    background: "#fde68a",
    borderRadius: 3,
    padding: "1px 6px",
  },
  ceremony: {
    padding: "12px 16px",
    background: "#fff",
    borderTop: "1px solid #e0e0e0",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    flexShrink: 0,
  },
  errorBanner: {
    background: "#fdecea",
    color: "#b3261e",
    border: "1px solid #f5c6c0",
    borderRadius: 6,
    padding: "6px 10px",
    fontSize: 13,
  },
  fieldLabel: { fontSize: 12, fontWeight: 600, color: "#444" },
  nameInput: {
    fontSize: 16,
    fontFamily: "'Segoe Script', 'Bradley Hand', cursive",
    padding: "8px 10px",
    border: "1px solid #dadce0",
    borderRadius: 6,
  },
  consentRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 13,
    color: "#333",
  },
  buttonRow: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
  },
  cancelBtn: {
    background: "none",
    border: "1px solid #dadce0",
    borderRadius: 6,
    padding: "8px 16px",
    fontSize: 14,
    cursor: "pointer",
  },
  signBtn: {
    background: "#0b57d0",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "8px 20px",
    fontSize: 14,
    fontWeight: 600,
  },
};
