/**
 * Generate the pre-connect discovery documents from src/config/landing.ts.
 *
 * Runs before `astro build` (see package.json `build`). Output lands in
 * `public/` so Astro copies it verbatim into `dist/`. `sirv` serves
 * `/.well-known/*` even though it is a dotfolder - well-known paths are exempt
 * from both its dotfile filter and the `--single` SPA fallback - so the static
 * card is reachable in production. The `start` script runs `sirv` with `--cors`
 * so registries/clients can fetch these docs cross-origin (SEP-2127 expects the
 * server card to be CORS-readable), matching the API route's CORS header.
 *
 * Single source of truth: edit branding in `landing.ts` (`site` + `serverCard`),
 * never hand-edit the generated JSON. Run `bun run gen:discovery` to refresh.
 *
 * The `tools[]` surface is NOT branding - its source of truth is the Python
 * `@service` registry, snapshotted to `tool-surface.generated.json` by
 * `scripts/export_tool_surface.py` (`make gen_tool_surface`). We read that
 * committed snapshot here so the card never drifts from the real tools and the
 * list lives in exactly one place - no hand-maintained copy in `landing.ts`.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { serverCard, site } from "../src/config/landing.ts";

const here = dirname(fileURLToPath(import.meta.url));
const publicDir = join(here, "..", "public");

const icon = {
  src: new URL("/favicon.svg", site.url).href,
  mimeType: "image/svg+xml",
  sizes: ["any"],
};
const repository = { url: site.githubUrl, source: serverCard.repositorySource };
const remotes = [{ type: "streamable-http", url: site.mcpUrl }];

interface Tool {
  name: string;
  description: string;
}

// Registry snapshot generated by scripts/export_tool_surface.py (committed).
const toolSurfacePath = join(here, "..", "src", "config", "tool-surface.generated.json");
const parsed = JSON.parse(readFileSync(toolSurfacePath, "utf8")) as unknown;
const tools: Tool[] = Array.isArray(parsed) ? (parsed as Tool[]) : [];
const toolsValid =
  tools.length > 0 &&
  tools.every((t): t is Tool => {
    if (typeof t !== "object" || t === null) return false;
    const o = t as Record<string, unknown>;
    return typeof o.name === "string" && typeof o.description === "string";
  });
if (!toolsValid) {
  throw new Error(
    `${toolSurfacePath} is empty or malformed; run \`make gen_tool_surface\` to regenerate it`,
  );
}

// SEP-2127 Server Card (the pre-connect discovery document). No `$schema`: the
// draft server-card schema is not published yet (the URL 404s), so emitting it
// would only break validators - matching the bare /.well-known/mcp.json doc.
// `serverUrl` (flat endpoint) and `tools[]` let agents preview where to connect
// and what the server can do before opening a transport; `remotes` carries the
// same endpoint in the SEP-2127 / registry shape.
const card = {
  name: serverCard.name,
  version: serverCard.version,
  title: site.name,
  description: serverCard.description,
  websiteUrl: site.url,
  serverUrl: site.mcpUrl,
  repository,
  icons: [icon],
  remotes,
  tools,
};

// MCP registry server.json (same identity, registry schema).
const registry = {
  $schema:
    "https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json",
  name: serverCard.name,
  title: site.name,
  description: serverCard.description,
  version: serverCard.version,
  websiteUrl: site.url,
  repository,
  icons: [icon],
  remotes,
};

function write(relPath: string, data: unknown): void {
  const out = join(publicDir, relPath);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, JSON.stringify(data, null, 2) + "\n");
  console.log(`✓ generated public/${relPath}`);
}

write(".well-known/mcp/server-card.json", card);
write("server.json", registry);
